---
- name: Is the host already registered?
  command: "subscription-manager status"
  register: subscribed
  changed_when: no
  ignore_errors: yes

- name: Clean RHSM
  command: subscription-manager clean

- name: Register host via Activation key
  redhat_subscription:
    activationkey: "{{ rhsm_activation_key }}"
    org_id: "{{ rhsm_org_id }}"
    state: present
    pool: "{{ rhsm_pool }}"
  when: rhsm_activation_key is defined and rhsm_activation_key
  register: register_key_result
  ignore_errors: yes

- name: Register host via username and password
  redhat_subscription:
    username: "{{ rhsm_user }}"
    password: "{{ rhsm_password }}"
    state: present
    pool: "{{ rhsm_pool }}"
  when: "('not registered' in subscribed.stdout or 'Current' not in subscribed.stdout) and rhsm_user is defined and rhsm_user"

- name: Disable automatic repositories
  command: subscription-manager repos --disable "*"

- name: Enable RHEL repositories by default
  command: "subscription-manager repos --enable {{ item }}"
  with_items: "{{ repos.rhel }}"

- name: Enable Satellite repositories when product == satellite
  command: "subscription-manager repos --enable {{ item }}"
  with_items:
    - "{{repos.satellite}}"
  when: product == "satellite"

- name: Enable OpenShift repositories when product == ocp
  command: "subscription-manager repos --enable {{ item }}"
  with_items:
    - "{{repos.ocp}}"
  when: product == "ocp"

- name: Enable CloudForms repositories when product == cfme
  command: "subscription-manager repos --enable {{ item }}"
  with_items:
    - "{{repos.cfme}}"
  when: product == "cfme"
